### ISSUE TITLE
이걸 뭐라고 해야하지..?

### ISSUE THREAD

**Issue by blugon09** [monun/kommand#17]
일단 Enable에다가 kommand를 넣었는데 에러가 났습니다

에러메세지
↓ 
```
[19:55:04 WARN]: [FishingRod] Loaded class kotlin.jvm.functions.Function1 from ExplosionProtection v1.0.1 which is not a depend, softdepend or loadbefore of this plugin.
[19:55:04 ERROR]: Error occurred while enabling FishingRod v1.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: io/github/monun/kommand/KommandKt
        at io.github.blugon0921.fishingrod.FishingRod.onEnable(FishingRod.kt:29) ~[FishingRod.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-349]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-349]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-349]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-349]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-349]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:730) ~[patched_1.17.1.jar:git-Paper-349]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-349]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[patched_1.17.1.jar:git-Paper-349]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-349]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.lang.ClassNotFoundException: io.github.monun.kommand.KommandKt
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[patched_1.17.1.jar:git-Paper-349]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-349]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 11 more
```

코드
↓
```kotlin
override fun onEnable() {
    logger.info("Plugin Enabled")
    Bukkit.getPluginManager().registerEvents(this, this)

    kommand {
        register("test") {
            requires { isPlayer }
            executes {
                val itemObject = ItemObject(Material.FISHING_ROD)
                itemObject.setEnchantment(Enchantment.DAMAGE_ALL, 0)
                itemObject.addItemFlag(ItemFlag.HIDE_ENCHANTS)

                player.inventory.addItem(itemObject.build())
            }
        }
    }
}
```

**Comment by dytroInc** [comment]
plugin.yml 보여주시겠어요?

**Comment by blugon09** [comment]
> plugin.yml 보여주시겠어요?

name: ${project.name}
version: ${project.version}
main: ${project.group}.${project.name.toLowerCase()}.${project.name}
api-version: 1.18
author: Blugon

**Comment by qogusdn1017** [comment]
음 libraries 항목 추가해주세요

**Comment by blugon09** [comment]
> 음 libraries 항목 추가해주세요

추가해도 안돼요

**Comment by dolphin2410** [comment]
`io.github.monun:paper-api:<version>`도 추가 해보세요. `io.github.monun:paper:<version>`에 포함이 안 됐던 것 같습니다.

**Comment by qogusdn1017** [comment]
> `io.github.monun:kommand-api:<version>`도 추가 해보세요. `io.github.monun:kommand:<version>`에 포함이 안 됐던 것 같습니다.

API는 필요없음

**Comment by dolphin2410** [comment]
근데 KommandKt가 없다는 것은 api에 있지 않나요?
