### ISSUE TITLE
[Bug] NoSuchMethodError

### ISSUE THREAD

**Issue by dolphin2410** [monun/kommand#18]
# Error:
` java.lang.NoSuchMethodError: 'int net.minecraft.core.BlockPosition.getX()'`

# Possible Cause
아마 매핑오류로 NMS의 `getX()`를 그대로 불러서 생기는 오류 같습니다. [blockPosition()](https://github.com/monun/kommand/blob/master/kommand-core/v1.18.1/src/main/kotlin/io/github/monun/kommand/v1_18_1/NMSKommandArgument.kt#L408)

# StackTrace:
```
Caused by: java.lang.NoSuchMethodError: 'int net.minecraft.core.BlockPosition.getX()'
        at io.github.monun.kommand.v1_18_1.NMSKommandArgumentSupport$blockPosition$1.invoke(NMSKommandArgument.kt:414) ~[?:?]
        at io.github.monun.kommand.v1_18_1.NMSKommandArgumentSupport$blockPosition$1.invoke(NMSKommandArgument.kt:409) ~[?:?]
        at io.github.monun.kommand.v1_18_1.NMSKommandArgumentKt$provide$1.invoke(NMSKommandArgument.kt:134) ~[?:?]
        at io.github.monun.kommand.v1_18_1.NMSKommandArgumentKt$provide$1.invoke(NMSKommandArgument.kt:133) ~[?:?]
        at io.github.monun.kommand.v1_18_1.NMSKommandArgument.from(NMSKommandArgument.kt:105) ~[?:?]
        at io.github.monun.kommand.v1_18_1.NMSKommandContext.get(NMSKommandContext.kt:57) ~[?:?]
        at io.github.monun.kommand.KommandContextKt.getValue(KommandContext.kt:37) ~[?:?]
        at io.github.monun.kommand.v1_18_1.NMSKommandKt.convert$lambda-14$lambda-12$lambda-11(NMSKommand.kt:136) ~[?:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[paper-1.18.1.jar:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177) ~[paper-1.18.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:291) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R1.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45) ~[paper-1.18.1.jar:git-Paper-81]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
```

# Steps To Reproduce
## Source Code
```kotlin
fun JavaPlugin.setupKommand() {
    kommand {
        register("mykommand") {
            then("arg" to blockPosition()) {
                executes { 
                    val arg: BlockPosition3D by it
                    val location arg.asVector.toLocation(player.world)
                    // Do whatever here
                }
            }
        }
    }
}
```
# Environment
- Paper 1.18.1
- PaperAPI 1.18.1
- Windows 11
- Java 17

**Comment by qogusdn1017** [comment]
BlockPosition3D가 머하는 애였죠

**Comment by dolphin2410** [comment]
`mykommand ~ ~ ~` 아니면 `mykommand 1 1 3`. 블록 위치를 나타내는 거요.

**Comment by qogusdn1017** [comment]
ㅇㅎ
