### ISSUE TITLE
1.19.2 / Paper / java.lang.LinkageError

### ISSUE THREAD

**Issue by GreenJJR** [monun/kommand#31]
아래는 에러코드 입니다.

```
[19:22:29 ERROR]: Error occurred while enabling Main v1.0-SNAPSHOT (Is it up to date?)
java.lang.LinkageError: loader constraint violation: loader java.net.URLClassLoader @77e7c6dd wants to load interface kotlin.jvm.functions.Function1. A different interface with the same name was previously loaded by 'nMain.jar' @54401299. (kotlin.jvm.functions.Function1 is in unnamed module of loader 'Main.jar' @54401299, parent loader java.net.URLClassLoader @7637f22)
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
    at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
    at java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
    at io.github.monun.kommand.KommandKt.kommand(Kommand.kt:44) ~[?:?]
    at io.group.Main.plugin.Main.onEnable(Main.kt:29) ~[Main.jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-153]
    at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-153]
    at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-153]
    at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-153]
    at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-153]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[paper-1.19.2.jar:git-Paper-153]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-153]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:22:29 INFO]: [Main] Disabling Main v1.0-SNAPSHOT
```

Build.gradle.kts Dependencies에 io.github.monun:kommand-api:2.14.0 추가했고 ShadowJar 사용하지 않고 있습니다.
그리고 plugin.yml에 io.github.monun:kommand-core:2.14.0 를 추가 했지만 같은 이름의 인터페이스가 로드되서 오류가 지속되고 있습니다.

**Comment by monun** [comment]
혹시 kotlin 라이브러리를 셰딩하셨나요?

**Comment by GreenJJR** [comment]
> 혹시 kotlin 라이브러리를 셰딩하셨나요?

Monun Docs에 있는 Kotlin 세팅 그대로 했습니다.

**Comment by qogusdn1017** [comment]
plugin.yml에 kotlin 관련 항목이 있으신지요?

**Comment by GreenJJR** [comment]
> plugin.yml에 kotlin 관련 항목이 있으신지요?

네 있습니다.
library에서 core를 불러오네요.

**Comment by qogusdn1017** [comment]
> > plugin.yml에 kotlin 관련 항목이 있으신지요?
> 
> 네 있습니다. library에서 core를 불러오네요.

Kommand 이외에 Kotlin 라이브러리를 한번 지워보실래요?
혹시 Kommand 이외에는 다른 항목이 없나요?

**Comment by GreenJJR** [comment]
> > > plugin.yml에 kotlin 관련 항목이 있으신지요?
> > 
> > 네 있습니다. library에서 core를 불러오네요.
> 
> Kommand 이외에 Kotlin 라이브러리를 한번 지워보실래요?
> 혹시 Kommand 이외에는 다른 항목이 없나요?

네 없습니다.

**Comment by GreenJJR** [comment]
build.gradle.kts -> dependencies
```
dependencies {
    compileOnly("io.papermc.paper:paper-api:1.19.2-R0.1-SNAPSHOT")

    implementation(kotlin("stdlib"))
    implementation("io.github.monun:kommand-api:2.14.0")


    testImplementation(kotlin("test"))
}
```

build.gradle.kts -> repositories
```
repositories {
    mavenCentral()
    mavenLocal()
    maven { url = uri("https://repo.papermc.io/repository/maven-public/") }
}
```

plugin.yml
```
name: Main
version: 1.0-SNAPSHOT
main: GroupID.Artifact.plugin.Main
api-version: 1.19
commands:
  sample:
    description: TEST COMMAND!
libraries:
  - io.github.monun:kommand-core:2.14.0
 ```

**Comment by qogusdn1017** [comment]
shadowJar를 쓰지 않는다면 상세 내용은 제 지식선으로는 모르겠습니다..
