### ISSUE TITLE
paper-mojmap-1.18.2-388.jar 에서 작동시 오류 발생

### ISSUE THREAD

**Issue by donghune** [monun/kommand#32]
paper-mojmap-1.18.2-388.jar 오류 발생
paper-1.18.2-388.jar 정상 작동

```
java.lang.ExceptionInInitializerError: null
	at io.github.monun.kommand.Kommand.<clinit>(Kommand.kt) ~[?:?]
	at io.github.monun.kommand.PluginKommand.register(Kommand.kt:39) ~[?:?]
	at io.github.donghune.AuctonCommand$initialize$1.invoke(AuctonCommand.kt:8) ~[terraria-auction.jar:?]
	at io.github.donghune.AuctonCommand$initialize$1.invoke(AuctonCommand.kt:7) ~[terraria-auction.jar:?]
	at io.github.monun.kommand.KommandKt.kommand(Kommand.kt:44) ~[?:?]
	at io.github.donghune.AuctonCommand.initialize(AuctonCommand.kt:7) ~[terraria-auction.jar:?]
	at io.github.donghune.AuctionPlugin.onEnable(AuctionPlugin.kt:11) ~[terraria-auction.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-388]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-388]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.reload(CraftServer.java:1016) ~[paper-1.18.2.jar:git-Paper-388]
	at org.bukkit.Bukkit.reload(Bukkit.java:909) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.18.2.jar:git-Paper-388]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:869) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:510) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:484) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.UnsupportedOperationException: io.github.monun.kommand.Kommand has an error occurred while creating the instance
	at io.github.monun.kommand.loader.LibraryLoader.loadNMS(LibraryLoader.kt:93) ~[?:?]
	at io.github.monun.kommand.loader.LibraryLoader.loadNMS$default(LibraryLoader.kt:54) ~[?:?]
	at io.github.monun.kommand.Kommand$Companion.<init>(Kommand.kt:27) ~[?:?]
	at io.github.monun.kommand.Kommand$Companion.<clinit>(Kommand.kt) ~[?:?]
	... 24 more
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at io.github.monun.kommand.loader.LibraryLoader.loadNMS(LibraryLoader.kt:82) ~[?:?]
	at io.github.monun.kommand.loader.LibraryLoader.loadNMS$default(LibraryLoader.kt:54) ~[?:?]
	at io.github.monun.kommand.Kommand$Companion.<init>(Kommand.kt:27) ~[?:?]
	at io.github.monun.kommand.Kommand$Companion.<clinit>(Kommand.kt) ~[?:?]
	... 24 more
Caused by: java.lang.NoSuchFieldError: vanillaCommandDispatcher
	at io.github.monun.kommand.v1_18_2.NMSKommand.<init>(NMSKommand.kt:45) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at io.github.monun.kommand.loader.LibraryLoader.loadNMS(LibraryLoader.kt:82) ~[?:?]
	at io.github.monun.kommand.loader.LibraryLoader.loadNMS$default(LibraryLoader.kt:54) ~[?:?]
	at io.github.monun.kommand.Kommand$Companion.<init>(Kommand.kt:27) ~[?:?]
	at io.github.monun.kommand.Kommand$Companion.<clinit>(Kommand.kt) ~[?:?]
	... 24 more
```
_Originally posted by @donghune in https://github.com/monun/kommand/issues/30#issuecomment-1297317982_

**Comment by monun** [comment]
mojmap은 개발용이라 작동하지 않을겁니다
