### ISSUE TITLE
Kommand does not support this version: v1_19_3

### ISSUE THREAD

**Issue by donghune** [monun/kommand#39]
이번에 있었던 이슈가 다시 발생하여 올립니다. 이전에 이슈는 해결하지 않고 그냥 순수 커맨드 써서 해결했었습니다..

JAR=/Users/yudonghun/.mcservers/paper/paper-mojmap-1.19.3-448.jar
MEMORY=4
BACKUP=false
RESTART=false
PLAYERS=100
PLUGINS=plugins-dev
WORLDS=worlds
PORT=-1
DEBUG_PORT=5005
JVM_TYPE=hotspot
Use Aikar's standard memory options
DEBUG MODE: JDK9+
Parameters: -Xmx4G -Xms4G -Dfile.encoding=UTF-8 -Dcom.mojang.eula.agree=true -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:InitiatingHeapOccupancyPercent=15 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar /Users/yudonghun/.mcservers/paper/paper-mojmap-1.19.3-448.jar -s100 -Pplugins-dev -Wworlds --nogui
Listening for transport dt_socket at address: 5005
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.1+12) Host: Mac OS X 10.16 (x86_64)
Loading libraries, please wait...

```
java.lang.ExceptionInInitializerError: null
	at io.github.monun.kommand.Kommand.<clinit>(Kommand.kt) ~[?:?]
	at io.github.monun.kommand.PluginKommand.register(Kommand.kt:48) ~[?:?]
	at io.github.donghune.josun.collected_crop.CollectedCropCommand$register$1.invoke(CollectedCropCommand.kt:12) ~[josun-0.0.1-SNAPSHOT-dev.jar:?]
	at io.github.donghune.josun.collected_crop.CollectedCropCommand$register$1.invoke(CollectedCropCommand.kt:11) ~[josun-0.0.1-SNAPSHOT-dev.jar:?]
	at io.github.monun.kommand.KommandKt.kommand(Kommand.kt:59) ~[?:?]
	at io.github.donghune.josun.collected_crop.CollectedCropCommand.register(CollectedCropCommand.kt:11) ~[josun-0.0.1-SNAPSHOT-dev.jar:?]
	at io.github.donghune.josun.JosunPlugin.onEnable(JosunPlugin.kt:14) ~[josun-0.0.1-SNAPSHOT-dev.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.3.jar:git-Paper-448]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.3.jar:git-Paper-448]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.19.3.jar:git-Paper-448]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:471) ~[paper-1.19.3.jar:git-Paper-448]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.19.3.jar:git-Paper-448]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-448]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.3.jar:git-Paper-448]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-448]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-448]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.UnsupportedOperationException: io.github.monun.kommand.Kommand does not support this version: v1_19_3
	at io.github.monun.kommand.loader.LibraryLoader.loadNMS(LibraryLoader.kt:84) ~[?:?]
	at io.github.monun.kommand.loader.LibraryLoader.loadNMS$default(LibraryLoader.kt:54) ~[?:?]
	at io.github.monun.kommand.Kommand$Companion.<init>(Kommand.kt:27) ~[?:?]
	at io.github.monun.kommand.Kommand$Companion.<clinit>(Kommand.kt) ~[?:?]
	... 19 more
Caused by: java.lang.ClassNotFoundException: Not found nms library class: [io.github.monun.kommand.v1_19_3.NMSKommand, io.github.monun.v1_19_3.kommand.NMSKommand]
	at io.github.monun.kommand.loader.LibraryLoader.loadNMS(LibraryLoader.kt:78) ~[?:?]
	at io.github.monun.kommand.loader.LibraryLoader.loadNMS$default(LibraryLoader.kt:54) ~[?:?]
	at io.github.monun.kommand.Kommand$Companion.<init>(Kommand.kt:27) ~[?:?]
	at io.github.monun.kommand.Kommand$Companion.<clinit>(Kommand.kt) ~[?:?]
	... 19 more
```

현재 작업중인 레포 첨부드립니다.
https://github.com/donghune/minecraft-josun

아래 레포지토리를 그대로 사용하였고 변경사항이라곤 toml 을 추가한게 다입니다. 다만 이것 때문에 발생할 것 같진 않습니다.
https://github.com/monun/paper-sample

서버 실행은 ./run dev 로 실행하였습니다.

**Comment by donghune** [comment]
추가로 확인된 사항은 paper-sample 기준 plugin.yml 의 libraries 영역에 io.github.monun:kommand-api 를 사용하고 있어 io.github.monun:kommand-core 로 변경시에는 발생하지 않습니다. 

io.github.monun:kommand-core 를 사용하였을 경우 아래와 같은 오류가 발생하는데 이는 #32 오류로 해결하면 될 것 같습니다.
java.lang.ExceptionInInitializerError: null
Caused by: java.lang.UnsupportedOperationException: io.github.monun.kommand.Kommand has an error occurred while creating the instance
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.lang.NoSuchFieldError: vanillaCommandDispatcher

정확하게 어떤게 맞는건지 궁금합니다

**Comment by donghune** [comment]
> paperweight-userdev 빼고

음.. 지금 문제가 버킷에서 NMS 관련 소스를 못 찾는다는 건데 따로 배포를 할께 아니라면 실행하는 버킷 자체에 NMS가 포함된걸로 실행 시켜도 되는걸까요?

**Comment by monun** [comment]
"./run dev"는 모장맵핑을 사용한 Paper를 실행합니다.

Tap이나 Kommand와 같은 라이브러리는 Maven Central에 올라갈 때 재난독화(reobf)됩니다.
모드 아티팩트(예: plugin.jar, mod.jar)에서 모장맵핑이 제거되어야 한다는 것으로 알고 있습니다.

그래서 "./run reobf"에서만 테스트가 가능합니다.

저도 Tap과 Kommand 라이브러리를 자주 사용하는데, 디버그나 스택 코드 핫스왑을 위해 해결 방법을 찾고 있습니다. 여유가 있을 때 솔루션을 만들어보겠습니다.

현재 가지고 있는 아이디어는 Git의 서브모듈(submodule)을 사용하여 서버 경로에 직접 배포하는 방법입니다.

그 외에도 다른 아이디어가 있다면 알려주세요.
